2023-02-14 17:08:46,589 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Configure stats pid to 3816
2023-02-14 17:08:46,590 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/.config/wandb/settings
2023-02-14 17:08:46,590 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/IC/wandb/settings
2023-02-14 17:08:46,590 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-14 17:08:46,590 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-14 17:08:46,590 INFO    MainThread:3816 [wandb_init.py:_log_setup():478] Logging user logs to /home/luigi-doria/IC/wandb/run-20230214_170846-y1gktlo0/logs/debug.log
2023-02-14 17:08:46,590 INFO    MainThread:3816 [wandb_init.py:_log_setup():479] Logging internal logs to /home/luigi-doria/IC/wandb/run-20230214_170846-y1gktlo0/logs/debug-internal.log
2023-02-14 17:08:46,591 INFO    MainThread:3816 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd3ea95d1e0>
2023-02-14 17:08:46,591 INFO    MainThread:3816 [wandb_init.py:init():518] calling init triggers
2023-02-14 17:08:46,591 INFO    MainThread:3816 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'architecture': 'Resnet18', 'N_ensemble': '5', 'Data_set': 'Cifar 100', 'temperatura': '1'}
2023-02-14 17:08:46,592 INFO    MainThread:3816 [wandb_init.py:init():571] starting backend
2023-02-14 17:08:46,592 INFO    MainThread:3816 [wandb_init.py:init():575] setting up manager
2023-02-14 17:08:46,604 INFO    MainThread:3816 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-14 17:08:46,607 INFO    MainThread:3816 [wandb_init.py:init():582] backend started and connected
2023-02-14 17:08:46,634 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-14 17:08:46,635 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-14 17:08:46,635 INFO    MainThread:3816 [wandb_init.py:init():670] updated telemetry
2023-02-14 17:08:46,649 INFO    MainThread:3816 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-14 17:08:47,785 INFO    MainThread:3816 [wandb_run.py:_on_init():2121] communicating current version
2023-02-14 17:08:47,842 INFO    MainThread:3816 [wandb_run.py:_on_init():2125] got version response upgrade_message: "wandb version 0.13.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-02-14 17:08:47,842 INFO    MainThread:3816 [wandb_init.py:init():758] starting run threads in backend
2023-02-14 17:08:50,826 WARNING MainThread:3816 [wandb_init.py:init():1129] interrupted
Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/luigi-doria/miniconda3/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/luigi-doria/miniconda3/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-02-14 17:10:06,587 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Configure stats pid to 3816
2023-02-14 17:10:06,587 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/.config/wandb/settings
2023-02-14 17:10:06,587 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/IC/wandb/settings
2023-02-14 17:10:06,587 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-14 17:10:06,588 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-14 17:10:06,588 INFO    MainThread:3816 [wandb_init.py:_log_setup():478] Logging user logs to /home/luigi-doria/IC/wandb/run-20230214_171006-pba8oc52/logs/debug.log
2023-02-14 17:10:06,588 INFO    MainThread:3816 [wandb_init.py:_log_setup():479] Logging internal logs to /home/luigi-doria/IC/wandb/run-20230214_171006-pba8oc52/logs/debug-internal.log
2023-02-14 17:10:06,588 INFO    MainThread:3816 [wandb_init.py:init():518] calling init triggers
2023-02-14 17:10:06,589 INFO    MainThread:3816 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'architecture': 'Resnet18', 'N_ensemble': '5', 'Data_set': 'Cifar 100', 'temperatura': '1'}
2023-02-14 17:10:06,589 INFO    MainThread:3816 [wandb_init.py:init():571] starting backend
2023-02-14 17:10:06,589 INFO    MainThread:3816 [wandb_init.py:init():575] setting up manager
2023-02-14 17:10:06,591 INFO    MainThread:3816 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-14 17:10:06,592 INFO    MainThread:3816 [wandb_init.py:init():582] backend started and connected
2023-02-14 17:10:06,597 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-14 17:10:06,597 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-14 17:10:06,597 INFO    MainThread:3816 [wandb_init.py:init():670] updated telemetry
2023-02-14 17:10:06,597 INFO    MainThread:3816 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-14 17:11:06,659 ERROR   MainThread:3816 [wandb_init.py:init():724] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-14 17:11:06,665 ERROR   MainThread:3816 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-14 17:11:45,225 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Configure stats pid to 3816
2023-02-14 17:11:45,225 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/.config/wandb/settings
2023-02-14 17:11:45,225 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/IC/wandb/settings
2023-02-14 17:11:45,225 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-14 17:11:45,225 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-14 17:11:45,225 INFO    MainThread:3816 [wandb_init.py:_log_setup():478] Logging user logs to /home/luigi-doria/IC/wandb/run-20230214_171145-rqy0xwsp/logs/debug.log
2023-02-14 17:11:45,225 INFO    MainThread:3816 [wandb_init.py:_log_setup():479] Logging internal logs to /home/luigi-doria/IC/wandb/run-20230214_171145-rqy0xwsp/logs/debug-internal.log
2023-02-14 17:11:45,226 INFO    MainThread:3816 [wandb_init.py:init():518] calling init triggers
2023-02-14 17:11:45,226 INFO    MainThread:3816 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'architecture': 'Resnet18', 'N_ensemble': '5', 'Data_set': 'Cifar 100', 'temperatura': '1'}
2023-02-14 17:11:45,226 INFO    MainThread:3816 [wandb_init.py:init():571] starting backend
2023-02-14 17:11:45,226 INFO    MainThread:3816 [wandb_init.py:init():575] setting up manager
2023-02-14 17:11:45,227 INFO    MainThread:3816 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-14 17:11:45,228 INFO    MainThread:3816 [wandb_init.py:init():582] backend started and connected
2023-02-14 17:11:45,236 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-14 17:11:45,236 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-14 17:11:45,237 INFO    MainThread:3816 [wandb_init.py:init():670] updated telemetry
2023-02-14 17:11:45,238 INFO    MainThread:3816 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-14 17:12:45,303 ERROR   MainThread:3816 [wandb_init.py:init():724] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-14 17:12:45,309 ERROR   MainThread:3816 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-14 17:13:22,433 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Configure stats pid to 3816
2023-02-14 17:13:22,434 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/.config/wandb/settings
2023-02-14 17:13:22,434 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/IC/wandb/settings
2023-02-14 17:13:22,434 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-14 17:13:22,434 INFO    MainThread:3816 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-14 17:13:22,434 INFO    MainThread:3816 [wandb_init.py:_log_setup():478] Logging user logs to /home/luigi-doria/IC/wandb/run-20230214_171322-b88ardu7/logs/debug.log
2023-02-14 17:13:22,434 INFO    MainThread:3816 [wandb_init.py:_log_setup():479] Logging internal logs to /home/luigi-doria/IC/wandb/run-20230214_171322-b88ardu7/logs/debug-internal.log
2023-02-14 17:13:22,435 INFO    MainThread:3816 [wandb_init.py:init():518] calling init triggers
2023-02-14 17:13:22,435 INFO    MainThread:3816 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'architecture': 'Resnet18', 'N_ensemble': '5', 'Data_set': 'Cifar 100', 'temperatura': '1'}
2023-02-14 17:13:22,435 INFO    MainThread:3816 [wandb_init.py:init():571] starting backend
2023-02-14 17:13:22,435 INFO    MainThread:3816 [wandb_init.py:init():575] setting up manager
2023-02-14 17:13:22,437 INFO    MainThread:3816 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-14 17:13:22,438 INFO    MainThread:3816 [wandb_init.py:init():582] backend started and connected
2023-02-14 17:13:22,453 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-14 17:13:22,453 INFO    MainThread:3816 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-14 17:13:22,454 INFO    MainThread:3816 [wandb_init.py:init():670] updated telemetry
2023-02-14 17:13:22,458 INFO    MainThread:3816 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-14 17:14:22,527 ERROR   MainThread:3816 [wandb_init.py:init():724] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-14 17:14:22,532 ERROR   MainThread:3816 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
