2023-02-16 13:05:20,474 INFO    MainThread:21932 [wandb_setup.py:_flush():68] Configure stats pid to 21932
2023-02-16 13:05:20,474 INFO    MainThread:21932 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/.config/wandb/settings
2023-02-16 13:05:20,474 INFO    MainThread:21932 [wandb_setup.py:_flush():68] Loading settings from /home/luigi-doria/IC/wandb/settings
2023-02-16 13:05:20,475 INFO    MainThread:21932 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-16 13:05:20,475 INFO    MainThread:21932 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-02-16 13:05:20,475 INFO    MainThread:21932 [wandb_init.py:_log_setup():478] Logging user logs to /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/logs/debug.log
2023-02-16 13:05:20,475 INFO    MainThread:21932 [wandb_init.py:_log_setup():479] Logging internal logs to /home/luigi-doria/IC/wandb/run-20230216_130520-zr31z4za/logs/debug-internal.log
2023-02-16 13:05:20,475 INFO    MainThread:21932 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd8b04a2fe0>
2023-02-16 13:05:20,476 INFO    MainThread:21932 [wandb_init.py:init():518] calling init triggers
2023-02-16 13:05:20,476 INFO    MainThread:21932 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'architecture': 'Resnet18', 'N_ensemble': '5', 'Data_set': 'Cifar 100', 'temperatura': '1', 'metodo': 'MSELOSS'}
2023-02-16 13:05:20,476 INFO    MainThread:21932 [wandb_init.py:init():571] starting backend
2023-02-16 13:05:20,476 INFO    MainThread:21932 [wandb_init.py:init():575] setting up manager
2023-02-16 13:05:20,480 INFO    MainThread:21932 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-16 13:05:20,482 INFO    MainThread:21932 [wandb_init.py:init():582] backend started and connected
2023-02-16 13:05:20,509 INFO    MainThread:21932 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-16 13:05:20,509 INFO    MainThread:21932 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-16 13:05:20,509 INFO    MainThread:21932 [wandb_init.py:init():670] updated telemetry
2023-02-16 13:05:20,512 INFO    MainThread:21932 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-16 13:05:21,006 INFO    MainThread:21932 [wandb_run.py:_on_init():2121] communicating current version
2023-02-16 13:05:21,043 INFO    MainThread:21932 [wandb_run.py:_on_init():2125] got version response upgrade_message: "wandb version 0.13.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-02-16 13:05:21,043 INFO    MainThread:21932 [wandb_init.py:init():758] starting run threads in backend
2023-02-16 13:05:23,241 INFO    MainThread:21932 [wandb_run.py:_console_start():2101] atexit reg
2023-02-16 13:05:23,241 INFO    MainThread:21932 [wandb_run.py:_redirect():1959] redirect: SettingsConsole.WRAP_RAW
2023-02-16 13:05:23,241 INFO    MainThread:21932 [wandb_run.py:_redirect():2024] Wrapping output streams.
2023-02-16 13:05:23,241 INFO    MainThread:21932 [wandb_run.py:_redirect():2046] Redirects installed.
2023-02-16 13:05:23,241 INFO    MainThread:21932 [wandb_init.py:init():798] run started, returning control to user process
2023-02-16 13:08:10,706 WARNING MsgRouterThr:21932 [router.py:message_loop():77] message_loop has been closed
2023-02-16 13:09:49,282 INFO    MainThread:21932 [wandb_init.py:_pause_backend():391] pausing backend
2023-02-16 13:09:49,282 INFO    MainThread:21932 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-02-16 13:15:42,354 INFO    MainThread:21932 [wandb_init.py:_resume_backend():400] resuming backend
2023-02-16 13:15:42,569 INFO    MainThread:21932 [wandb_init.py:_pause_backend():391] pausing backend
2023-02-16 13:15:42,569 INFO    MainThread:21932 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-02-16 13:15:48,094 INFO    MainThread:21932 [wandb_init.py:_resume_backend():400] resuming backend
2023-02-16 13:15:48,269 ERROR   MainThread:21932 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1105, in init
    wi.setup(kwargs)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 195, in setup
    with telemetry.context(obj=self._init_telemetry_obj) as tel:
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 692, in _telemetry_callback
    self._telemetry_flush()
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 703, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/luigi-doria/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-02-16 13:15:50,401 INFO    MainThread:21932 [wandb_init.py:_pause_backend():391] pausing backend
2023-02-16 13:15:50,401 INFO    MainThread:21932 [jupyter.py:save_ipynb():379] not saving jupyter notebook
